<a href="https://colab.research.google.com/github/gvogiatzis/CS4740/blob/main/CS4740_Lab_Week_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [CS4740 Labs] Week 6: Deep Generative Models

##Introduction

One of the big successes of Deep Learning that sparked significant interest in the last few years is Deep Generative Models. These are deep neural architectures whose main goal is *analysis-by-synthesis*. In other words, they represent an attempt to analyse a complex dataset by synthesizing new datapoints that preserve the statistical properties of the original data. In achieving this, the deep generative models are able to extract meaningful information about the statistical distribution that gave rise to the original dataset, thereby providing us with some sort of *high-level understanding*. 

These Deep Generative architectures have been used to generate realistic data from a variety of sources, including among others, celebrity face images and artistic paintings!

In this lab we will explore some of the properties of Deep Generative Models by running several experiments using popular generative architectures. 

## Transpose convolutions

Before we can 

In [4]:
import numpy as np

w = [2,1,-3,-1]

N = 10

W=[]

for i in range(N):
    W.append(np.correlate([i==I for I in range(N)],w,mode='valid'))
W = np.array(W)
print(W)

Wt=[]
M=N-len(w)+1

for i in range(M):
    Wt.append(np.convolve([i==I for I in range(M)],w,mode='full'))

Wt = np.array(Wt).T
print(Wt)

[[ 2  0  0  0  0  0  0]
 [ 1  2  0  0  0  0  0]
 [-3  1  2  0  0  0  0]
 [-1 -3  1  2  0  0  0]
 [ 0 -1 -3  1  2  0  0]
 [ 0  0 -1 -3  1  2  0]
 [ 0  0  0 -1 -3  1  2]
 [ 0  0  0  0 -1 -3  1]
 [ 0  0  0  0  0 -1 -3]
 [ 0  0  0  0  0  0 -1]]
[[ 2  0  0  0  0  0  0]
 [ 1  2  0  0  0  0  0]
 [-3  1  2  0  0  0  0]
 [-1 -3  1  2  0  0  0]
 [ 0 -1 -3  1  2  0  0]
 [ 0  0 -1 -3  1  2  0]
 [ 0  0  0 -1 -3  1  2]
 [ 0  0  0  0 -1 -3  1]
 [ 0  0  0  0  0 -1 -3]
 [ 0  0  0  0  0  0 -1]]


In [2]:
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

In [ ]:
conv = nn.Conv1d()